/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/models/track.glb --types
*/
import React from 'react'

import { useGLTF } from '@react-three/drei'

import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Street003_-_applied_transform']: THREE.Mesh
  }
  materials: {}
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/track.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes['Street003_-_applied_transform'].geometry}
        material={nodes['Street003_-_applied_transform'].material}
      />
    </group>
  )
}

useGLTF.preload('/track.glb')
